logicalclocks/hops-util

pom.xml

HOPSWORKS-480

---

pom.xml

HOPSWORKS-540

---

pom.xml

HOPSWORKS-838

---

src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java

[HOPSWORKS-911] Cache featurestore metadata on client

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/exceptions/CannotWriteImageDataFrameException.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java

- Add more datatypes for training datasets

[HOPSWORKS-912] Support image and avro in FS

---

README.md
pom.xml
src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/WorkflowManager.java
src/main/java/io/hops/util/exceptions/HTTPSClientInitializationException.java
src/main/java/io/hops/util/exceptions/JWTNotFoundException.java
src/main/java/io/hops/util/featurestore/FeaturegroupsAndTrainingDatasetsDTO.java

ApplicationService client requests are removed and replaced with FeatureStore and Kafka service requests.

HOPSWORKS-827

---

src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/dtos/FeatureDTO.java
src/main/java/io/hops/util/featurestore/ops/FeaturestoreOp.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeaturegroupPartitions.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateTrainingDataset.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoFeaturegroup.java

- Allow the user to specify feature group partitioning in the API

[HOPSWORKS-1025] add hive partitioning to featuregroups

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/exceptions/HiveNotEnabled.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/FeaturestoreOp.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeature.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeaturegroupPartitions.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeatures.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadTrainingDataset.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreSQLQuery.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateTrainingDataset.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoTrainingDataset.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateFeaturegroupStats.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateTrainingDatasetStats.java

- verify that sparkSQL session has hive enabled

[HOPSWORKS-1131][featurestore]

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/Hops.java

Add option for insecure hostname verification

[HOPSWORKS-1095] Add back localhost

---

src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/FeaturestoreOp.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeaturegroup.java

[HOPSWORKS-1196] append

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/FeaturestoreRestClient.java
src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/FeaturestoreOp.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreSyncHiveTable.java

- Integrate Hudi with Hopsworks Feature Store

[HOPSWORKS-34] Hudi for unified Stream/Batch processing

---

src/main/java/io/hops/util/FeaturestoreRestClient.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/FeaturestoreOp.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadOnlineConnector.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreDisableFeaturegroupOnline.java

[HOPSWORKS-1142] append

---

src/main/java/io/hops/util/exceptions/OnlineFeaturestoreNotEnabled.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/FeaturestoreOp.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeature.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeaturegroupPartitions.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreReadFeatures.java
src/main/java/io/hops/util/featurestore/ops/read_ops/FeaturestoreSQLQuery.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateTrainingDataset.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreEnableFeaturegroupOnline.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreImportFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoTrainingDataset.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateFeaturegroupStats.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateTrainingDatasetStats.java

- improve error messages when online featurestore is not enabled

[HOPSWORKS-1142][online featurestore] append

---

src/main/java/io/hops/util/featurestore/dtos/FeaturestoreDTO.java

[HOPSWORKS-1140] append

---

src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/FeaturestoreOp.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateTrainingDataset.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreEnableFeaturegroupOnline.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreImportFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoFeaturegroup.java

Merge instead of #61 
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1378
We decided to keep the API the same with primaryKey instead of changing it to primaryKeys.

[HOPSWORKS-1378][featurestore][append] composite key DDL support

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/FeaturestoreRestClient.java
src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/featurestore/dtos/featuregroup/CachedFeaturegroupDTO.java
src/main/java/io/hops/util/featurestore/dtos/featuregroup/FeaturegroupDTO.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreInsertIntoFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateFeaturegroupStats.java

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1380

[HOPSWORKS-1380][featurestore] Configure Feature Group statistics during creation

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java

exclude non numeric columns also from descriptive statistics
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1443

[HOPSWORKS-1443][featurestore] Spark returning Infinity values for mean statistics of string type features

---

src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateTrainingDataset.java

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1424

[HOPSWORKS-1424][featurestore] Handle upper/lower case for feature group names

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/exceptions/ElasticAuthorizationTokenException.java

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1476
tests: https://github.com/logicalclocks/hops-testing/pull/567

[HOPSWORKS-1476] Add support for elasticsearch spark connector

---

src/main/java/io/hops/util/FeaturestoreRestClient.java
src/main/java/io/hops/util/Hops.java
src/main/java/io/hops/util/featurestore/FeaturestoreHelper.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateFeaturegroupStats.java

Fixing a javadoc error introduced by the previous PR and fixing some additional ones that caused warnings. Needed so Jenkins can build the jar.

[HOPSWORKS-1627][append] Fix javadocs

---

src/main/java/io/hops/util/Constants.java
src/main/java/io/hops/util/featurestore/dtos/featuregroup/FeaturegroupDTO.java
src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreCreateFeaturegroup.java

Fix hudi compatibility. I set everything to NONE, which means disabled hudi time travel format

[HOPSWORKS-1374] Add Hudi API to HSFS and commits to the FeatureStore
